### ISSUE TITLE
Virtual memory on SPI SRAM? 

### ISSUE THREAD

**Issue by vitasam** [robinhedwards/ArduinoBASIC#3]
Hello,

what do you think about adding virtual RAM ( https://github.com/rhelmus/virtmem )? 

I did quick experiment with virtmem project by allocating a virtual buffer of 128000 bytes on  23LC1024 SPI SRAM chip:
```
  char testbuf[] = "This is a test string buffer\nThis is a test string buffer\nThis is a test string buffer\nThis is a test string buffer\nThis is a test string buffer\nThis is a test string buffer\nThis is a test string buffer";
    
    // Allocate a char buffer in virtual memory and store the address to a virtual pointer
    VPtr<char, SPIRAMVAlloc> str = valloc.alloc<char>(128000);    
    VPtr<char, SPIRAMVAlloc> ptr = str;

    // Set 'A' to first 65000 bytes of the buffer 
    memset(str, 'A', 65000);
    Serial.print("Read from str[0]: "); Serial.println(str[0]);

    // Get byte from the offset 10 of virtual pointer 
    char a= *(ptr + 10);
    Serial.print("char a= *(ptr + 10): "); Serial.println(a);

    // Set 'H' to the offset 100000 of virtual pointer 
    *(ptr + 100000) = 'H';
    char h = *(ptr + 100000);
    Serial.print("char h = *(ptr + 100000): "); Serial.println(h);

    // Set 'B' to array index 60000
    str[60000] = 'B';
    Serial.print("Read from str[60000]: "); Serial.println(str[60000]);

    // Set 'C' to array index 126000
    str[126000] = 'C';
    Serial.print("Read from str[126000]: "); Serial.println(str[126000]);

   // Copy another buffer in to the virtual buffer
    memcpy(&str[127200], testbuf, sizeof(testbuf));
    memset(testbuf, 0, sizeof(testbuf));
    memcpy(testbuf, &str[127200], sizeof(testbuf));
    Serial.print("Read from str[127200]: "); Serial.println(testbuf);

    valloc.free(str); // Free the virtual memory
```

Result:
```Read from str[0]: A
char a= *(ptr + 10): A
char h = *(ptr + 100000): H
Read from str[60000]: B
Read from str[126000]: C
Read from str[127200]: This is a test string buffer
This is a test string buffer
This is a test string buffer
This is a test string buffer
This is a test string buffer
This is a test string buffer
This is a test string buffer
```

**Comment by vitasam** [comment]
Replaced **oled** class to I2C LCD 16x2 in my DIY ZX81 basic-shield :)
![arduino_basic_1328](https://user-images.githubusercontent.com/5597505/36447832-37c662d4-168e-11e8-824c-3377bcbc1b77.jpg)

**Comment by robinhedwards** [comment]
Nice idea about the virtual memory - I hadn't heard of this before.
Feel free to fork the project and have a go at adding it, since I doubt I'll have time in the near future to return to this project.

Robin

**Comment by vitasam** [comment]
Thank you! It took literally ~20 min to replace OLED function calls. I definitely will fork your project (very nice one!) and will try to do step by step: add serial terminal input instead PS/2 (as a debug option) and then add support for ZX81 matrix. And if I will have time I will try to add virtual mem project with 128 KB chip available for BASIC. 

The key words - "if I will have time" :)

**Comment by vitasam** [comment]
Replaced PS/2 keyboard calls to Serial terminal.
The code:
```
10 a=2
20 b=3.4
30 c=a/b
40 print "c=";c
run
print "Hello world!"
```

I made a pull request.

**Comment by jamesrussell42** [comment]
I would be very happy to see the code with the OLED and PS2 keyboard replaced for serial.

**Comment by vitasam** [comment]
> I would be very happy to see the code with the OLED and PS2 keyboard replaced for serial.

The code is in my[ pull-request to current GIT repo](https://github.com/robinhedwards/ArduinoBASIC/pull/5)
OLED and PS2 keyboard are replaced with serial LCD and serial terminal

[Link ](https://1drv.ms/v/s!AnelMDA4LECOgZhMgl145cwX1drLSA)to LCD and Serial terminal video

**Comment by jamesrussell42** [comment]
Thanks :) i've been playing around with the code, working great for serial input.

I am now trying to implement serial output as well, removing the LCD and OLED entirely.

I have found code from https://github.com/BleuLlama/TinyBasicPlus that implements serial output for Tiny Basic but it looks a bit beyond my abilities to integrate the two.

**Comment by vitasam** [comment]
> 
> 
> Thanks :) i've been playing around with the code, working great for serial input.
> 
> I am now trying to implement serial output as well, removing the LCD and OLED entirely.
> 
> I have found code from https://github.com/BleuLlama/TinyBasicPlus that implements serial output for Tiny Basic but it looks a bit beyond my abilities to integrate the two.

Actually I've started with serial-only input/output before adding the support for serial LCD. Later I've migrated to [stm32 "Blue Pill" board](https://wiki.stm32duino.com/index.php?title=Blue_Pill) with this Basic and added SD card support (screenshots [#1](https://1drv.ms/u/s!AnelMDA4LECOgZhNLA4Ni7aQnPftNg) and [#2](https://1drv.ms/u/s!AnelMDA4LECOgZhOmdEyr1MTXXbLDw)  from 20x4 Serial LCD), but at some point I abandoned the project and deleted the GIT repository :(

I also tested that TinyBasic but not that much - it is integer-only and the code itself is a kind of mess.

If you have some active GIT repo to play around I could try to contribute there :)

**Comment by jamesrussell42** [comment]
Ah, blue pill board looks good.  Never tried one, I will have to do some research.

I have been playing with this project the last couple days: https://i.imgur.com/lLCW9as.jpg

I have got a C64 keyboard hooked up to one Arduino outputting serial and I have a 20x4 LCD hooked up working as a serial monitor.  On a third Arduino I have Tiny Basic Plus running taking the Serial input from keyboard and outputting to a screen.

This all works great but as you say Tiny Basic is too limited, I wanted a more fully featured basic running and found this project.

I have implemented your changes to add serial keyboard and LCD but I am having a couple troubles with implementing serial only out/input, when adding serial out instead of LCD out the console is constantly being written to and refreshed by the flash character function.  Also it seems that the serial input is reading the serial output and getting in a mess.

If you would be willing to take a look at my code that would be very appreciated :)

I have put all my code onto this repo: https://github.com/jamesrussell42/BASICcomp

Thanks very much and thank you for your work on this.

**Comment by vitasam** [comment]
> C64 keyboard hooked up to one Arduino outputting serial 

Wow, this sounds very interesting! Is this an original C64 keyboard or some modern clones? 

Thanks for the GIT repo, I made a fork. Maybe I will get dust out of my Arduino and try to modify my pull-request code for serial input/output only :)

**Comment by jamesrussell42** [comment]
Yes all original C64 Keyboard :)

I found an existing project to convert it to serial but all the mappings were wrong so I had to rewrite that was not a fun task, still not perfect but enough to use BASIC with.

If you fancy giving it a try I will send you over the pinout for it.

If you could help me with this I would be very grateful, I am a laravel developer by trade so lower level things are a bit beyond me, I am learning though and this project is a great excuse to learn.
